updated button color
Talentrator/Prograchallenges.com pull request #44
Opened 2021-12-06 19:41 UTC by james-muriithi

most of the changes in the theme.scss were made by prettier, i added from line 453 and white variable on line 102

2021-12-08 09:13 UTC, Wittmaxi requested changes
This is what code reviews are for! You have done excellent work, now we need to align our visions of good code and good design so we can work as one Team 😁

2021-12-08 09:13 UTC, Wittmaxi commented on frontend/src/components/ChallengeCard.vue
> +      <!-- <b-col cols="3">
Don't commit commented-out code!

2021-12-08 09:13 UTC, Wittmaxi commented on frontend/src/components/ChallengeCard.vue
> +      if (this.challenge.title.length > 20) {
A ternary might be cleaner. What do you think?

2021-12-08 09:13 UTC, Wittmaxi commented on frontend/src/components/ChallengeCard.vue
> +        return this.challenge.text.slice(0, 500) + `... <b-link to="${this.challengeLink}" class="more text-primary">More</b-link>`;
the link Seems malformed. Have you checked that it works?

2021-12-08 09:13 UTC, Wittmaxi commented on frontend/src/components/ChallengeCard.vue
> +        <p class="challenge-description" v-html="challengeDescription"></p>
Using v-html here Seems hacky. Just put in the b-link in and add a v.if

2021-12-08 09:13 UTC, Wittmaxi commented on frontend/src/components/ChallengeCard.vue
> +    challengeLink(){
Good!

2021-12-08 09:13 UTC, Wittmaxi commented on frontend/src/components/ChallengeCard.vue
> +.challenge {
I'm not a huge fan of having a lot of CSS - You decide what you want, but it's important that the designs stay consistent within Talentrator and Prograchall

2021-12-08 09:22 UTC, james-muriithi commented on frontend/src/assets/scss/partials/_animations.scss
> +@keyframes shakeError {
They were in the theme.scss file, i just put them in a separate file

2021-12-08 09:22 UTC, james-muriithi commented on frontend/src/components/ChallengeCard.vue
> +      if (this.challenge.title.length > 20) {
yes

2021-12-08 11:27 UTC, james-muriithi commented on frontend/src/assets/scss/partials/_animations.scss
> +@keyframes shakeError {
removed

2021-12-08 11:28 UTC, james-muriithi commented on frontend/src/components/ChallengeCard.vue
> +        return this.challenge.text.slice(0, 500) + `... <b-link to="${this.challengeLink}" class="more text-primary">More</b-link>`;
yes it was malformed, thanks

2021-12-08 11:29 UTC, james-muriithi commented on frontend/src/components/ChallengeCard.vue
> +.challenge {
okay

2021-12-11 14:25 UTC, Wittmaxi approved these changes
Very good! :)

2021-12-11 14:25 UTC, Wittmaxi commented on frontend/src/pages/challenges/single-challenge/FormulateComment.vue
> +            >{{previewMarkdown ? "Continue Editing": "Preview"}}
these brackets are misformatted

2021-12-14 19:25 UTC, Wittmaxi requested changes
Hey James!
Great work, Stuff seems to be working great! :)
Clean code is super important! This is why it's important that every piece of code follows the SRP from the beginning! How about you work with Rishabh on coding one Component that displays Markdown with our code-editor?

2021-12-14 19:25 UTC, Wittmaxi commented on frontend/src/pages/challenges/single-challenge/FormulateComment.vue
> +    categorizeCodeSnippetsAndText(text) {
Code is reused from Comment.vue

2021-12-14 19:25 UTC, Wittmaxi commented on frontend/src/pages/challenges/single-challenge/FormulateComment.vue
> +    langToEditor: {
Code is reused from Comment.vue

2021-12-14 19:25 UTC, Wittmaxi commented on frontend/src/pages/challenges/single-challenge/FormulateComment.vue
> +              v-for="(description, idx) in categorizeCodeSnippetsAndText(
Code is reused from Comment.vue

2021-12-14 19:25 UTC, Wittmaxi commented on frontend/src/pages/challenges/single-challenge/FormulateComment.vue
> +              class="form__input"
does `form__input` exist?

2021-12-14 19:25 UTC, Wittmaxi commented on frontend/src/pages/challenges/single-challenge/FormulateComment.vue
> +    markdownToHtml(markdown) {
This same challenge was solved differently in Comment.vue

2021-12-15 06:51 UTC, james-muriithi commented on frontend/src/pages/challenges/single-challenge/FormulateComment.vue
> +              class="form__input"
there is one style for transition

2021-12-18 17:33 UTC, Wittmaxi approved these changes

2021-12-20 09:06 UTC, merged