James changes
Talentrator/Prograchallenges.com pull request #49
Opened 2022-01-07 07:32 UTC by james-muriithi

2022-01-07 13:15 UTC, Wittmaxi requested changes
Additionally to this feedback, the two icons (test-failed/test-passed) seem to be unused. Please make sure everything commited is also actually being used

2022-01-07 13:15 UTC, Wittmaxi commented on frontend/src/components/code-editor/ChallengeModule.vue
> +                <div class="" v-if="!erronoeusResult(result)">
"erronoeusResult" is a typo and maybe a bit too sophisticated for a function name

2022-01-07 13:15 UTC, Wittmaxi commented on frontend/src/components/stepper/SecondStep.vue
> +        { text: "Javascript", value: "javascript-node" },
is this list used in other places? If so, it would make sense to export it globally

2022-01-07 13:15 UTC, Wittmaxi commented on frontend/src/pages/challenges/CreateChallenge.vue
> +    changeStep(step, stepper = false) {
This function seems a bit long winded? Is there a way to generalize the validations to make the function smaller and easier to maintain?

2022-01-07 13:55 UTC, james-muriithi commented on frontend/src/components/code-editor/ChallengeModule.vue
> +                <div class="" v-if="!erronoeusResult(result)">
😂😂😂i am not so good with naming

2022-01-07 13:55 UTC, james-muriithi commented on frontend/src/components/stepper/SecondStep.vue
> +        { text: "Javascript", value: "javascript-node" },
I think it is

2022-01-07 13:56 UTC, james-muriithi commented on frontend/src/pages/challenges/CreateChallenge.vue
> +    changeStep(step, stepper = false) {
Okay

2022-01-08 14:42 UTC, james-muriithi commented on frontend/src/components/stepper/SecondStep.vue
> +        { text: "Javascript", value: "javascript-node" },
Just confirmed, its not used in other places

2022-01-12 12:10 UTC, Wittmaxi commented on frontend/src/components/ChallengeCard.vue
> +      const challengeVote = firebase.functions().httpsCallable("challengeVote");
Why have two different functions for voting on a challenge and for voting on a test? Why not have a generic "vote" function which is linked to by the challenge? Would that work?

2022-01-12 12:12 UTC, Wittmaxi commented on frontend/src/components/Voting.vue
> +<template>
Good idea on separating this!

2022-01-12 12:14 UTC, Wittmaxi commented on frontend/src/components/Voting.vue
> +      if (!this.userUpvoted) {
Cleaner:
```
if (this.userUpvoted) return;
```

2022-01-12 12:15 UTC, Wittmaxi commented on frontend/src/components/Voting.vue
> +.votes {
This styling seems a bit over-the top. Can this be achieved through the normal bootstrap-classes?

2022-01-12 12:17 UTC, Wittmaxi commented on functions/src/challenges/challenge_vote.js
> +    const InputData = mySchema.parse({ challengeId, method, votes })
variables and constants need to be camelCase

2022-01-12 12:18 UTC, Wittmaxi commented on functions/src/challenges/insert_challenge.js
> +    await admin.firestore().collection('challenges').doc(uid).set({...inputData, creationTime: getTimeStampOfNow(), score: 0, votes: 0 });
Votes should be a separate collection, in challenge, you can save the "voteId" - that way you can use the same voting system for everything that can be voted on!

2022-01-12 13:07 UTC, james-muriithi commented on functions/src/challenges/insert_challenge.js
> +    await admin.firestore().collection('challenges').doc(uid).set({...inputData, creationTime: getTimeStampOfNow(), score: 0, votes: 0 });
won't saving the votes on a separate collection cause performance to slow down cause of the claculations?

2022-01-12 13:08 UTC, james-muriithi commented on functions/src/challenges/challenge_vote.js
> +    const InputData = mySchema.parse({ challengeId, method, votes })
okay, will change that

2022-01-13 08:27 UTC, james-muriithi commented on frontend/src/components/Voting.vue
> +    vote(method, value = 1) {
Cause i need to capture if a user upvoted or downvoted to disable them from doing it twice

2022-01-13 08:44 UTC, Wittmaxi commented on functions/src/challenges/insert_challenge.js
> +    await admin.firestore().collection('challenges').doc(uid).set({...inputData, creationTime: getTimeStampOfNow(), score: 0, votes: 0 });
You can fetch them asynchronously together

2022-01-13 08:45 UTC, Wittmaxi commented on frontend/src/components/Voting.vue
> +    vote(method, value = 1) {
Good thinking! But that should not be handled by the "vote" function - the only job of the "vote" function is to update the scores. SRP! ;)

2022-01-13 09:23 UTC, james-muriithi commented on frontend/src/components/Voting.vue
> +.votes {
the padding, the hover and active colors i dont think so

2022-01-13 11:30 UTC, james-muriithi commented on functions/src/challenges/insert_challenge.js
> +    await admin.firestore().collection('challenges').doc(uid).set({...inputData, creationTime: getTimeStampOfNow(), score: 0, votes: 0 });
Could you kindly share a schema for the votes collection

2022-01-13 19:05 UTC, Wittmaxi commented on functions/src/challenges/insert_challenge.js
> +    await admin.firestore().collection('challenges').doc(uid).set({...inputData, creationTime: getTimeStampOfNow(), score: 0, votes: 0 });
![image](https://user-images.githubusercontent.com/16443184/149393243-d4f00817-25b2-43c1-92d8-fa57bddaf16b.png)
can you agree to this schema?

2022-01-13 19:05 UTC, Wittmaxi commented on frontend/src/components/Voting.vue
> +.votes {
Okay

2022-01-18 10:21 UTC, Wittmaxi approved these changes
Just 1-2 things - very impressive! :)

2022-01-18 10:21 UTC, Wittmaxi commented on frontend/src/components/ChallengeCard.vue
> +  mixins: [ProgrammingLanguagesMixin],
"ProgrammingLanguagesMixin" is redundant - why not Just "ProgrammingLanguages"?

2022-01-18 10:21 UTC, Wittmaxi commented on frontend/src/components/Navbar.vue
> +          ><span class="text-white">Challenges</span></b-nav-item
the brackets here are weird

2022-01-18 10:21 UTC, Wittmaxi commented on frontend/src/components/Navbar.vue
> +        <!-- <li class="nav-item align-self-center ps-4 pe-3" v-else>
No commented-out code in the repo!

2022-01-18 10:21 UTC, Wittmaxi commented on frontend/src/components/challenge/TagsSection.vue
> +        >{{ formatTag(tag) }}</router-link
the tags indentation seems weird

2022-01-18 10:21 UTC, Wittmaxi commented on frontend/src/components/form/TagsInput.vue
> +        this.$emit("valuechange", value);
Could this work with the v-model interface? In that case, you would need to emit another signal

2022-01-18 10:26 UTC, james-muriithi commented on frontend/src/components/form/TagsInput.vue
> +        this.$emit("valuechange", value);
i don't understand

2022-01-18 10:29 UTC, james-muriithi commented on frontend/src/components/Navbar.vue
> +        <!-- <li class="nav-item align-self-center ps-4 pe-3" v-else>
my bad, i forgot to delete, i was testing something

2022-01-31 06:40 UTC, merged