Challenges component on Home Page
Talentrator/Prograchallenges.com pull request #6
Opened 2021-09-19 12:21 UTC by ShantanuLamba

2021-09-19 16:57 UTC, aman2712 submitted a review, later dismissed
This is just one change I found, you can fix it and it might be ready for production

2021-09-19 16:57 UTC, aman2712 commented on frontend/src/pages/toplevel/home/Challenges.vue
> +          <b-col><button class="button-random mt-2">RANDOM</button></b-col>
the correct way to use this button is:
`<b-button variant="primary" block class="mt-2"> </b-button>`

2021-09-19 16:57 UTC, aman2712 commented on frontend/src/pages/toplevel/home/Challenges.vue
> +.button-random {
You don't need this class as I mentioned in my last comment

2021-09-19 16:59 UTC, ShantanuLamba commented on frontend/src/pages/toplevel/home/Challenges.vue
> +.button-random {
Thanks I will do it

2021-09-20 05:12 UTC, Wittmaxi requested changes
Far better than your last PR! Just some very small details that you couldn't have known since we never talked about them as they are rather specific!

2021-09-20 05:12 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/Challenges.vue
> +      <center>
Use class `text-center` on parent or (for block-level elements with fixed width) `mx-auto`

2021-09-20 05:12 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/Challenges.vue
> +        <h1 class="pb-2" style="font-size: 3.5rem">C h a l l e n g e s</h1>
Please stick to the bootstrap-fontsizes to guarantee consistency. If you need a bigger font-size, use `display-<1-4>` (defined by bootstrap)

2021-09-20 05:12 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/Challenges.vue
> +      <p style="letter-spacing: 1.4px">
Please stick to the default letter-spacing to guarantee consistency

2021-09-20 05:12 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/Challenges.vue
> +        <center>
There is no need to center a block-level element

2021-09-20 05:12 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/Challenges.vue
> +      <div>
Those div's have no effect and only clutter the file

2021-09-20 05:12 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/Challenges.vue
> +      <div>
those divs have no effect and only clutter the file

2021-09-20 05:19 UTC, ShantanuLamba commented on frontend/src/pages/toplevel/home/Challenges.vue
> +        <h1 class="pb-2" style="font-size: 3.5rem">C h a l l e n g e s</h1>
is that a class?

2021-09-20 05:31 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/Challenges.vue
> +        <h1 class="pb-2" style="font-size: 3.5rem">C h a l l e n g e s</h1>
https://getbootstrap.com/docs/4.0/utilities/display/

2021-09-20 05:43 UTC, merged