Fix footer
Talentrator/Prograchallenges.com pull request #7
Opened 2021-09-19 16:19 UTC by aman2712

2021-09-19 16:36 UTC, ShantanuLamba commented
Our theme is black not white ig and the footer should drag down (maybe add some margin)

2021-09-19 16:40 UTC, ShantanuLamba commented
Everything is fine, I reviewed

2021-09-19 17:00 UTC, aman2712 commented
> Our theme is black not white ig and the footer should drag down on the create challenges page(maybe add some margin)

It will automatically come down when you add a section on top of it

2021-09-20 05:06 UTC, Wittmaxi requested changes
Pretty good, please export the SVGs and merge!

2021-09-20 05:06 UTC, Wittmaxi commented on frontend/src/components/Footer.vue
> +            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telegram" viewBox="0 0 16 16">
Please import the SVGs as a file - we might want to reuse the icons + it makes the HTML-code easier to read

2021-09-20 05:20 UTC, merged