[REF:CreateChallenge.vue|SingleChallenge.vue|theme.scss] added new fi…
Talentrator/Prograchallenges.com pull request #8
Opened 2021-09-20 10:41 UTC by aman2712

…elds to forms

2021-09-20 11:34 UTC, ShantanuLamba commented
Everything is fine !

2021-09-20 18:19 UTC, Wittmaxi requested changes

2021-09-20 18:19 UTC, Wittmaxi commented on frontend/src/pages/create-challenge/CreateChallenge.vue
> +            <!-- <div class="d-md-flex p-2"> -->
No commented-out code! 

https://kentcdodds.com/blog/please-dont-commit-commented-out-code

2021-09-20 18:19 UTC, Wittmaxi commented on frontend/src/pages/single-challenge/SingleChallenge.vue
> +            console.log('email >>>', this.form.email)
no console log in commits (unless required by implementation)

2021-09-20 18:19 UTC, Wittmaxi commented on frontend/src/pages/single-challenge/SingleChallenge.vue
> +              <div v-for="item in comments" :key="item.index" :class="{'mt-3': true, 'my-2': true, 'border-bottom': (comments.indexOf(item) + 1 !== comments.length), 'border-secondary': true}">
You can mix `class` and `:class`

Please use the former for styles that always apply!

2021-09-20 18:19 UTC, Wittmaxi commented on frontend/src/pages/single-challenge/SingleChallenge.vue
> +                <b-row>
This file should be in the folder for challenges, not in a separate folder!

2021-09-21 07:24 UTC, Wittmaxi requested changes

2021-09-21 07:24 UTC, Wittmaxi commented on frontend/src/pages/challenges/create-challenge/CreateChallenge.vue
> +                <b-col lg='6' md='12'>
please be consistent with " and '

2021-09-21 07:24 UTC, Wittmaxi commented on frontend/src/theme.scss
> +  primary: #c07095,
?

2021-09-21 08:23 UTC, merged