Home page sections(Features and About Us)
Talentrator/Prograchallenges.com pull request #9
Opened 2021-09-20 13:44 UTC by ShantanuLamba

2021-09-20 18:13 UTC, Wittmaxi requested changes

2021-09-20 18:13 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/othersections.vue
> +          title="Code </> & Learn"
`&` needs to be escaped - use ```&amp;```

2021-09-20 18:13 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/othersections.vue
> +        <b-card
B-card is not flexible enough for most uses and ends up becoming unclean code - please implement the required behaviour yourself using border-utilities in bootstrap

2021-09-20 18:13 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/othersections.vue
> +          style="max-width: 20rem"
Avoid external styles

2021-09-20 18:13 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/othersections.vue
> +          style="max-width: 20rem"
avoid external styles

2021-09-20 18:13 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/othersections.vue
> +        <b-card
no b-card

2021-09-20 18:13 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/othersections.vue
> +      <b-col>
Specify the amount of cols for each element to get more control over responsiveness

2021-09-20 18:13 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/othersections.vue
> +.divider{
Please use https://getbootstrap.com/docs/4.5/utilities/borders/

2021-09-20 18:13 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/othersections.vue
> +@media only screen and (max-width: 600px) {
The breakpoint you are looking for is @media screen and (min-width: 768px) - PLEASE use the breakpoints specified by bootstrap in order to have consistent behaviour

2021-09-20 18:13 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/othersections.vue
> +    border-right: none;
A better design would be completely floating cards or a full border

Two design principles that usually help: 
1) Every element has a genuine purpose
2) every element has room to breathe

2021-09-20 18:13 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/othersections.vue
> +@media only screen and (max-width: 600px) {
Or avoid media queries in general ;-)

2021-09-20 18:13 UTC, Wittmaxi commented on frontend/src/pages/toplevel/Home.vue
> +    <OtherSections/>
Component name is not descriptive

2021-09-20 18:13 UTC, Wittmaxi commented on frontend/src/pages/toplevel/Home.vue
> +import OtherSections from "./home/othersections.vue";
For filenames, please follow the following guideline: 


```
    for Vue-Files, use PascalCase
    for Javascript-Files, use snake_case
    for folders, prefer kebab-case
```

2021-09-21 02:24 UTC, ShantanuLamba commented on frontend/src/pages/toplevel/home/othersections.vue
> +.divider{
This does not work, I have already tried making it with bootstrap, css is the only option if we want divider

2021-09-21 02:25 UTC, ShantanuLamba commented on frontend/src/pages/toplevel/home/othersections.vue
> +          style="max-width: 20rem"
This styling came when I copy pasted this from bootstrap-vue website, but don't worry I am replacing b-card

2021-09-21 02:29 UTC, ShantanuLamba commented on frontend/src/pages/toplevel/Home.vue
> +    <OtherSections/>
Please suggest a name then

2021-09-21 03:21 UTC, ShantanuLamba commented on frontend/src/pages/toplevel/home/othersections.vue
> +@media only screen and (max-width: 600px) {
https://getbootstrap.com/docs/4.0/layout/overview/

I have already used the right breakpoint

2021-09-21 03:24 UTC, ShantanuLamba commented on frontend/src/pages/toplevel/home/othersections.vue
> +    border-right: none;
Full border or no border doesn't look good, divider makes it beautiful

2021-09-21 07:18 UTC, merged

2021-09-21 07:21 UTC, Wittmaxi requested changes

2021-09-21 07:21 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/othersections.vue
> +@media only screen and (max-width: 600px) {
Are we reading the same webpage? there Are the specified breakpoints

```// Extra small devices (portrait phones, less than 576px)
@media (max-width: 575.98px) { ... }

// Small devices (landscape phones, less than 768px)
@media (max-width: 767.98px) { ... }

// Medium devices (tablets, less than 992px)
@media (max-width: 991.98px) { ... }

// Large devices (desktops, less than 1200px)
@media (max-width: 1199.98px) { ... }

// Extra large devices (large desktops)
// No media query since the extra-large breakpoint has no upper bound on its width````

2021-09-21 07:21 UTC, Wittmaxi commented on frontend/src/pages/toplevel/home/othersections.vue
> +    border-right: none;
I will implement a better design later, reducing clutter